### ISSUE TITLE
New detail view of feedback does not provide sufficient details

### ISSUE THREAD

**Issue by zaanposni** [line/abc-user-feedback#267]
I am not sure if this intended or not. If so, please feel free to close this issue.

Since version `5.2414.51`. The detail view of a feedback no longer includes custom fields.
Therefore, if a user enters a long text, it is only visible in the table itself. Which is a bit weird to read.

I feel like the old approach was much better with displaying all custom fields in the details panel as well.

![image](https://github.com/line/abc-user-feedback/assets/24491035/6e0140fa-8494-4763-b629-22625927bb88)

![image](https://github.com/line/abc-user-feedback/assets/24491035/e8da0a73-6f57-4d94-8a76-7c223eb0d43e)

**Comment by h4l-yup** [comment]
@zaanposni 

Actually, we changed nothing on the feedback detail view.
Therefore it should work as before.

We tried to re-generate your situation but we could not.

Can you take some screen shots of browser's network tab while loading feedback detail view?
We want to check if the field information is being loaded well on the API call.

<img width="730" alt="image" src="https://github.com/line/abc-user-feedback/assets/28913065/d0dffd22-0dbe-42ce-9881-56c3c5e90851">

**Comment by h4l-yup** [comment]
@zaanposni 

According to your screenshot, it seems you made your own fields with type `DEFAULT`.
However the DEFAULT type is not intended to be made by yourself. It is only for automatically made fields.

As I know, there is no way to make custom field with DEFAULT type with our admin web UI.
If you did not modify the field directly in mysql, there might be some bugs in somewhere.

For you information, in the upcoming version, there will be breaking changes in field type.
As we develop the `webhook feature` and other external API endpoints, the terms of `API` and `ADMIN` field types become kind of awkward.
We will deprecate type in field and make property (read-only, editable) in field instead.
Migration script would be included.

Anyway I think the problem of feedback detail is caused by the field type so if you want to fix, change the types of fields into `API` if those fields are collecting by feedback creation API.

**Comment by zaanposni** [comment]
Yep you are right. Changing type to `API` fixed my issue.
I have created those fields using the API directly, back when the web UI did not have the option to manage fields :)
